### ISSUE TITLE
Stack deploy with configs failed `read /data/compose/3: is a directory`

### ISSUE THREAD

**Issue by kaotika** [greenled/portainer-stack-utils#20]
Hi, I am on search for easy stack deployment through portainer instead of docker cli and stumbled over this great tool.

It took me a short time to find out how to compile the binary from master, cause the release is outdated. But then it worked like a charm.

I tried to deploy a simple nginx stack with a few traefik labels. I'am using a local traefik reverse proxy with self signed tls certificate for local development. If I deploy the stack without the `configs`, the stack is ok. With `configs` included, the deployment failed (verbose and debug set true). I created the configs by hand in portainer and deployment with `docker stack deploy -c stack.1.yml test` worked like expected.

* error log
```bash
psu stack deploy test -c stack.1.yml

2019/08/02 16:12:24 [Using config file: /home/developer/.psu.yaml]
2019/08/02 16:12:24 [Getting all stacks...]
2019/08/02 16:12:24 [Get stacks request
---
Method: GET
URL: https://docker.local.com/api/stacks?filters={}
Body:

---]
2019/08/02 16:12:24 [Get stacks response
---
Status: 200 OK
Body:
[{"Id":3,"Name":"test","Type":1,"EndpointId":1,"SwarmId":"tk8alsobbjuc147jot4p84gj8","EntryPoint":"docker-compose.yml","Env":[{"name":"domain","value":"test.local.com"}],"ProjectPath":"/data/compose/3","ResourceControl":{"Id":0,"ResourceId":"","SubResourceIds":null,"Type":0,"UserAccesses":null,"TeamAccesses":null,"Public":false}}]

---]
2019/08/02 16:12:24 [Getting stack test...]
2019/08/02 16:12:24 [Stack test found. Updating...]
2019/08/02 16:12:24 [Update stack request
---
Method: PUT
URL: https://docker.local.com/api/stacks/3?endpointId=1
Body:
{"StackFileContent":"version: '3.7'\n\nservices:\n  server:\n    image: nginx:alpine\n    deploy:\n      labels:\n        \"traefik.enable\": \"true\"\n        \"traefik.port\": \"80\"\n        \"traefik.docker.network\": \"web\"\n        \"traefik.frontend.rule\": \"Host:${domain:-test.local.com}\"\n        \"traefik.backend.loadbalancer.method\": \"wrr\"\n        \"traefik.frontend.headers.SSLRedirect\": \"true\"\n    configs:\n      - source: index.html\n        target: /usr/share/nginx/html/index.html\n    networks:\n      external:\n\nnetworks:\n  external:\n    external: true\n    name: web\n\nconfigs:\n  index.html:\n    external: false\n    name: index.html","Env":[{"name":"domain","value":"test.local..com"}],"Prune":false}
---]
2019/08/02 16:12:24 [Update stack response
---
Status: 500 Internal Server Error
Body:
{"err":"read /data/compose/3: is a directory\n","details":"read /data/compose/3: is a directory\n"}

---]
2019/08/02 16:12:24 Error: read /data/compose/3: is a directory
: read /data/compose/3: is a directory
```

* `stack.1.yml`
```yaml
version: '3.7'

services:
  server:
    image: nginx:alpine
    deploy:
      labels:
        "traefik.enable": "true"
        "traefik.port": "80"
        "traefik.docker.network": "web"
        "traefik.frontend.rule": "Host:${domain:-test.local.com}"
        "traefik.backend.loadbalancer.method": "wrr"
        "traefik.frontend.headers.SSLRedirect": "true"
    configs:
      - source: index.html
        target: /usr/share/nginx/html/index.html
    networks:
      external:

networks:
  external:
    external: true
    name: web

configs:
  index.html:
    external: false
    name: index.html
```

* `index.hml`
```
<!DOCTYPE html>
<html>
<body>

<h1>My First Heading</h1>
<p>My first paragraph.</p>

</body>
</html> 
```

**Comment by greenled** [comment]
Hi @kaotika  

I'm glad you liked this tool. The error you are getting happens when you neither mark a config as external (`external: false`) or specify a file to load it from (`file: null`). It will happen both in Portainer and in `docker stack deploy` command.

According to the [Compose file version 3 reference](https://docs.docker.com/compose/compose-file/) "The source of the config is either `file` or `external`". Portainer only supports `external` configs, as it only accepts the stack file content and no additional files to load the configs from. You have to create the config first, then deploy/update the stack and reference the config as external (`external: true`). **So far**, only the latest can be done through this tool so, you will have to create the config in Portainer by hand.

As you noted, the latest release ([0.1.1](https://github.com/greenled/portainer-stack-utils/releases/0.1.1)) is a bit outdated, but it's still the most stable one and the recommended for production environments. In that version you could achieve the same result with:

```bash
./psu -a deploy -l https://docker.local.com -u USER -p PASSWORD -n test -c stack.1.yml
```

The version in `master` branch has it's advantages, like zero external dependencies and a simpler sintax, but it's still unreleased and it's API is likely to suffer changes.

Nevertheles, this issue brings to light an interesting use case where one would want to deploy stacks with `file` configs in Portainer (in a single step), just like you would do with `docker stack deploy` command. It could be a nice addition to this project. From [Portainer API docs](https://app.swaggerhub.com/apis/deviantony/Portainer/1.21.0):

    Portainer **DO NOT** expose specific endpoints to manage your Docker resources (create a container, remove a volume, etc...).

    Instead, it acts as a reverse-proxy to the Docker HTTP API. This means that you can execute Docker requests **via** the Portainer HTTP API.

**Comment by kaotika** [comment]
Thanks for quick answer.
Seems I really missed the `external: false` flag...my fault.

Are their any plans to support config/secret creation? If so I vote for it. :+1:

**Comment by greenled** [comment]
There could be. Would you help me shape the idea? Like how would it look like, how would you use it, how does it work with similar tools, are there corner cases, a single file o several ones, which format...? Please fill a new issue with this info. I'm closing this one.
